### ISSUE TITLE
Tests failing when using --doctest-modules

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-db#135]
After upgrading `pytest-invenio` to version `1.4.0` and applying changes, tests started failing.
The issue is the `pytest` argument `--doctest-modules` in the file `pytest.ini` but the cause is not clear.

The 3 tests that are failing are the ones using the decorator:
`@patch('pkg_resources.iter_entry_points', _mock_entry_points)`

For the time being, the argument `--doctest-modules` has been removed.

**Comment by lnielsen** [comment]
Closing as won't fix
