### ISSUE TITLE
installation: unpin for sqlalchemy v1.4, sqlalchemy-utils v0.36+, flask-sqlalchemy v2.5+

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-db#147]
Currently we're pinning SQLAlchemy <1.4, sqlalchemy-utils<0.36, flask-sqlalchemy<2.5. 

All of these pins are related. Currently, e.g. sqlalchemy-utils is not compatible with SQLAlchemy v1.4, while Flask-SQLAlchemy v2.5 was just release and is compatible with v1.4. There's a PR for SQLAlchemy-Utils - see the issue: https://github.com/kvesteri/sqlalchemy-utils/issues/505

**Comment by lnielsen** [comment]
sqlalchemy-utils v0.37.0 is out with support for v1.4

**Comment by lnielsen** [comment]
In  ``setup.py`` try to change requirements to:

```python
install_requires = [
    'invenio-base>=1.2.3',
    'Flask-Alembic>=2.0.1',
    'Flask-SQLAlchemy>=2.1,<2.6.0',
    'SQLAlchemy>=1.2.18,<1.5.0',
    'SQLAlchemy-Utils>=0.33.1,<0.38',
]
```

Submit a PR and see if tests passes.

**Comment by ines-cruz** [comment]
I created a [PR](https://github.com/inveniosoftware/invenio-db/pull/148) with the changes described in this issue
I ran the tests and they passed
What should be the next step?

**Comment by ppanero** [comment]
Try to create a new RDM instance and install locally invenio-db (`invenio-cli packages install...`), then just play a bit with it (create a record, publish etc.) If no errors then 🚀

**Comment by lnielsen** [comment]
So in the end, when I ran the CI tests there was errors: https://github.com/inveniosoftware/invenio-db/runs/2517395617?check_suite_focus=true

**Comment by lnielsen** [comment]
SQLAlchemy-Continuum also has a problem with v1.4 - see kvesteri/sqlalchemy-continuum#255 - seems to be the laster blokcer for an upgrade
