### ISSUE TITLE
setup: `db init` when PostgreSQL database exists

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-db#15]
When installing Invenio v3.0 on PostgreSQL, and when the database already exists, the `db init` command leads to troubles, see Invenio's kickstart scripts.  Investigate this.

**Comment by jirikuncar** [comment]
- one can use http://sqlalchemy-utils.readthedocs.org/en/latest/database_helpers.html#database-exists

**Comment by tiborsimko** [comment]
Unfortunately that's not enough due to `template1` business that SQLAlchemy-Utils is doing:

```console
$ git grep -C 2 template1
sqlalchemy_utils/functions/database.py-
sqlalchemy_utils/functions/database.py-    if url.drivername.startswith('postgresql'):
sqlalchemy_utils/functions/database.py:        url.database = 'template1'
sqlalchemy_utils/functions/database.py-    elif not url.drivername.startswith('sqlite'):
sqlalchemy_utils/functions/database.py-        url.database = None
```

Hence I'll push a PR against `Invenio-DB` and amend Invenio's kickstart scripts at the same time to include `template1` to the list of permitted databases.  This fixes the issue.
