### ISSUE TITLE
types: support for LocalProxy on PostgreSQL

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-db#33]
SQLAlchemy + PostgreSQL does not handle Werkzeug's LocalProxy when used in queries.
E.g. [this PR](https://github.com/inveniosoftware/invenio-deposit/pull/82) add a call to ``str`` around the ``key`` in ``record.files[str(key)`` in order to ensure the a string is passed down instead of a LocalProxy. This should however not be necessary and was already fixed in Invenio 2.0 - most likely using the feature:
http://docs.sqlalchemy.org/en/latest/core/compiler.html#changing-compilation-of-types

**Comment by jirikuncar** [comment]
@lnielsen can you include a traceback without the patch on Deposit?
