### ISSUE TITLE
global: force naming convention

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-db#62]
As we discussed during [IDF](https://indico.cern.ch/event/586915/) we should force naming conventions for PK, FK, ... Please read: http://docs.sqlalchemy.org/en/latest/core/constraints.html#configuring-constraint-naming-conventions

**Comment by lnielsen** [comment]
Is this about the a) column names, b) constraint/index names or c) both? Reading briefly the SQLAlchemy documentation it seems to only deal with constraint/index naming conventions and not column naming conventions.

**Comment by jirikuncar** [comment]
>  force naming conventions for PK, FK, ...

@lnielsen it's for Alembic. I have explained in during IDF. See also http://alembic.zzzcomputing.com/en/latest/naming.html (pointed from just above http://docs.sqlalchemy.org/en/latest/core/constraints.html#naming-check-constraints)

**Comment by tiborsimko** [comment]
@drjova @egabancho @jirikuncar @krzysztof @lnielsen @nharraud @slint @tiborsimko OK to advance on this one? It'll be really useful for the future Invenio 3.0 production.. I had already put up my vote above 😄 

@jirikuncar Can you take Zenodo DB dump as an example and see about forcing PK/FK names there?

**Comment by lnielsen** [comment]
Do we know what the impact is on the existing modules - i.e. do we have many repos to update after this?

**Comment by jirikuncar** [comment]
@lnielsen I will try to prepare a generic upgrade recipe which should update names of constraints, indexes, and primary keys (if possible). Basically, we need to update only modules that are installed at the time when the upgrade is run.
