### ISSUE TITLE
global: constraint naming generates too long names for mysql/pg

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-db#69]
The constraint naming conventions introduced in #65 seems to be generating names without taking MySQL/PostgreSQL limitations into account.

It also seems like that it's not possible to override the naming convention in order to set a name within the limits. The causes problems for e.g. oauthclient/oauth2server and other modules where constraint names generated are too long.

 I've tried to produce a minimal [breaking PR](https://github.com/inveniosoftware/invenio-db/pull/68/commits/444f8be200a217b5057d65ef822ccd454b100b0e) that demonstrates the problem.

Best would be if it was possible to just override the name for a given constraint if the name generated is too long. If that's not possible we may need to remove the naming conventions again, and force that models explicitly specify a constraint name.

**Comment by egabancho** [comment]
It is funny as they claim it has been fixed:
- https://bitbucket.org/zzzeek/sqlalchemy/issues/1412/automatically-generated-index-name-is-too
- https://bitbucket.org/zzzeek/sqlalchemy/commits/b2c0b50bbfa43f662afd16b7ca51bcfe17e4c351

**Comment by slint** [comment]
I already encountered this with @jirikuncar in [`invenio-communities`](https://github.com/inveniosoftware/invenio-communities/pull/95/files#diff-4380fd733e4a4e8917c45813a49b38edR84). Explicitly naming the index is possible and fixes the issue, though as @egabancho mentioned, there's already supposed to be a length check for this in `sqlalchemy`... Maybe the "fix" is just the fact that the creation procedure fails?

Also in case we start naming indices, we should come up with a sane and non-conflicting naming convention.

**Comment by egabancho** [comment]
I think the problem now is with Alembic and not SQLAlchemy, https://travis-ci.org/inveniosoftware/invenio-db/jobs/198803454#L491

**Comment by lnielsen** [comment]
It's me making a mistake. Actually it do work by explicitly specifying the constraint name, in the PR i'm just missing to specify constraint names for the other constraints.
