### ISSUE TITLE
``instance`` directory is missing

### ISSUE THREAD

**Issue by kiryx** [inveniosoftware/invenio-db#7]
This is perhaps a non issue but this:

https://github.com/inveniosoftware/invenio-db/blob/master/invenio_db/core.py#L58 will request a sqlite database at something like "./instance/testapp.db".

will cause the following error at the first testing of a new module:
```text
OperationalError: (sqlite3.OperationalError) unable to open database file
```

becase the ``instance`` directory is not in the cookiecutted by default.

It seems that sqlite cannot create an extra directory, but it can create the ``testapp.db`` file once the directory ``instance`` is in place.
So this is either a ticket for cookiecutter template to include the ``instance`` dir, or (which I believe to be better) changing the default path to the root of the repo and add it to the ``.gitignore``.

**Comment by jirikuncar** [comment]
The test fixture should take care about this.

**Comment by kiryx** [comment]
If I understand correctly that would imply boilerplate to each test writing to db. Perhaps putting the db file in ``tests/`` or even creating a directory ``tests/instance`` in each module requiring db for testing ?

**Comment by lnielsen** [comment]
I had a similar issue. I think there's two ways to solve it:

1) In memory db
```python
app = Flask('testapp')
app.config.update(SQLALCHEMY_DATABASE_URI='sqlite://', TESTING=True,)
```

2) Set instance path to temporary directory
```python
@pytest.fixture()
def script_info(request):
    instance_path = tempfile.mkdtemp()
    app = Flask(__name__, instance_path=instance_path)

    def teardown():
        shutil.rmtree(instance_path)

    request.addfinalizer(teardown)
    return app
```

Probably (2) is the best, since for Travis we might test both SQLite, Postgres and MySQL so (1) wouldn't work in that case.

**Comment by jirikuncar** [comment]
:+1: (2)

**Comment by kiryx** [comment]
OK, I guess that resolves the issue. I'm sticking with 2) from now on.
