### ISSUE TITLE
cli: db drop leaves two tables

### ISSUE THREAD

**Issue by dinosk** [inveniosoftware/invenio-db#72]
In relation to [#195](https://github.com/inveniosoftware/invenio-accounts/issues/195) in invenio-accounts, after creating the database with:
`flask alembic upgrade heads`

dropping the tables: `flask db drop` leaves these two in the db:
```
+----------+-----------------+--------+----------+
| Schema   | Name            | Type   | Owner    |
|----------+-----------------+--------+----------|
| public   | alembic_version | table  | postgres |
| public   | transaction     | table  | postgres |
+----------+-----------------+--------+----------+
```

For the transaction table, alembic downgrade would delete it fine but it is not currently found in this [loop](https://github.com/inveniosoftware/invenio-db/blob/master/invenio_db/cli.py#L83) <- this is wrong, it is registered but can't be dropped because of the transaction_id_seq depending on it.

**Comment by jirikuncar** [comment]
The `alembic_version` table is not part of `db.metadata` hence we need to clear it manually:

```python
#drop alembic_version table
if db.engine.dialect.has_table(db.engine, 'alembic_version'):
    version = db.Table('alembic_version', db.metadata, autoload_with=db.engine)
    version.drop()
```

The `transaction` table should be registered by `SQLAlchemy-Continuum` and dropped automatically. It needs some deeper investigation.

**Comment by dinosk** [comment]
The error with the `transaction` table was the default nextval for the id that is added by alembic PrimaryConstraint and `flask db drop` was raising:
```sqlalchemy.exc.InternalError: (psycopg2.InternalError) cannot drop sequence transaction_id_seq because other objects depend on it
DETAIL:  default for table transaction column id depends on sequence transaction_id_seq
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
 [SQL: 'DROP SEQUENCE transaction_id_seq']
```
When creating the table as in [#74](https://github.com/inveniosoftware/invenio-db/pull/74) the table created by `flask db create` and `flask alembic upgrade heads` are identical.

flask db create:
```
+-------------+-----------------------------+-------------+
| Column      | Type                        | Modifiers   |
|-------------+-----------------------------+-------------|
| issued_at   | timestamp without time zone |             |
| id          | bigint                      |  not null   |
| remote_addr | character varying(50)       |             |
+-------------+-----------------------------+-------------+
Indexes:
    "pk_transaction" PRIMARY KEY, btree (id)
```

flask alembic upgrade heads:
```
+-------------+-----------------------------+-----------------------------------------------------------+
| Column      | Type                        | Modifiers                                                 |
|-------------+-----------------------------+-----------------------------------------------------------|
| issued_at   | timestamp without time zone |                                                           |
| id          | bigint                      |  not null default nextval('transaction_id_seq'::regclass) |
| remote_addr | character varying(50)       |                                                           |
+-------------+-----------------------------+-----------------------------------------------------------+
Indexes:
    "pk_transaction" PRIMARY KEY, btree (id)
```

About the alembic_version table should I add the manual drop in the cli drop command?

**Comment by jirikuncar** [comment]
@dinosk can you check: `current_app.extensions['invenio-db'].versioning_manager.transaction_cls.__table__.drop()`

**Comment by dinosk** [comment]
@jirikuncar sorry for the late reply. I get the same error:
```
     79 @with_appcontext
     80 def drop(verbose):
     81     """Drop tables."""
     82     click.secho('Dropping all tables!', fg='red', bold=True)
     83     with click.progressbar(reversed(_db.metadata.sorted_tables)) as bar:
     84         import ipdb
     85         ipdb.set_trace()
---> 86         for table in bar:
     87             if verbose:
     88                 click.echo(' Dropping table {0}'.format(table))
     89             table.drop(bind=_db.engine, checkfirst=True)
     90     click.secho('Dropped all tables!', fg='green')
     91 

ipdb> current_app.extensions['invenio-db'].versioning_manager.transaction_cls.__table__.drop(bind=_db.engine, checkfirst=True)
*** sqlalchemy.exc.InternalError: (psycopg2.InternalError) cannot drop sequence transaction_id_seq because other objects depend on it
DETAIL:  default for table transaction column id depends on sequence transaction_id_seq
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
 [SQL: 'DROP SEQUENCE transaction_id_seq']
```
In the first comment that I mispoke about the transaction table not being found in  `_db.metadata.sorted_tables`, the error is better described in the second comment.
What do you think about: 
```
if op._proxy.migration_context.dialect.supports_sequences:
        op.execute(CreateSequence(Sequence("transaction_id_seq")))
```

**Comment by jirikuncar** [comment]
@dinosk maybe we should remove the progress bar and use `drop_all` instead. The implementation https://bitbucket.org/zzzeek/sqlalchemy/src/69adef7ed56cbd3d37e41cc2a552976688f63acb/lib/sqlalchemy/sql/ddl.py?at=master&fileviewer=file-view-default#ddl.py-826 is taking care about removing the sequences correctly.

**Comment by dinosk** [comment]
This was a bit complicated, all of the following result in the same sequence error, even if I try dropping the sequence first:
```
1. 
_db.metadata.drop_all(_db.engine)

2. 
schema_dropper = SchemaDropper(_db.engine.dialect, _db.engine.connect())
seq_coll = [s for s in _db.metadata._sequences.values()]

for seq in seq_coll:
        schema_dropper.traverse_single(seq, drop_ok=True)
```

After reading this: https://bitbucket.org/zzzeek/sqlalchemy/issues/3676/defaults-sequences-assigned-to-both-python

I tried dropping the table first by: 
```
schema_dropper.connection.execute(
        schema.DropTable(table))
```
and it worked. This is I think raw SQL disguised hehe but it is the only way I could do the dropping without changing the alembic revision that creates it.

**Comment by jirikuncar** [comment]
@dinosk good investigation and 👍  for `schema.DropTable(table)`

**Comment by dinosk** [comment]
@jirikuncar thank you!
